package decompile.apk.activity;

import Constant.Constant;
import android.content.Intent;
import android.graphics.Bitmap.CompressFormat;
import android.graphics.BitmapFactory;
import android.os.Bundle;
import android.os.Environment;
import android.util.Log;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.Button;
import android.widget.EditText;
import androidx.appcompat.app.AppCompatActivity;
import com.asharinfotech.muslimweddingcard.R;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.Font.FontFamily;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.html.HtmlTags;
import com.itextpdf.text.pdf.CMYKColor;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;

public class FamilyDetailsActivity extends AppCompatActivity {
    public String address_line1;
    public String address_line2;
    public String age;
    private Button back;
    public String blood_group;
    public String caste;
    public String complexion;
    public String district;
    public String dob;
    public String education_address;
    public String education_details;
    public String education_details_three;
    public String education_details_two;
    public String father_name;
    public String fathers_occupation;
    public String full_name;
    public String gotra;
    public String grand_father_name;
    public String grand_mother_name;
    public String height;
    public String income_details;
    public EditText input_father_name;
    public String input_father_name1;
    public EditText input_fathers_occupation;
    public String input_fathers_occupation1;
    public EditText input_grand_father_name;
    public String input_grand_father_name1;
    public EditText input_grand_mother_name;
    public String input_grand_mother_name1;
    public EditText input_married_brothers;
    public String input_married_brothers1;
    public EditText input_married_sisters;
    public String input_married_sisters1;
    public EditText input_maternal_uncle_aunt;
    public EditText input_mother_name;
    public String input_mother_name1;
    public EditText input_mothers_occupation;
    public String input_mothers_occupation1;
    public EditText input_parental_uncle_aunt;
    public EditText input_parents_contact_number;
    public String input_parents_contact_number1;
    public EditText input_partner_expectations;
    public String input_partner_expectations1;
    public EditText input_total_brothers;
    public String input_total_brothers1;
    public EditText input_total_sisters;
    public String input_total_sisters1;
    public String mangal;
    public String married_brothers;
    public String married_sisters;
    public String mother_name;
    public String mothers_occupation;
    private Button next;
    private Button next2;
    public String occupation_details;
    public String parents_contact;
    public String partner_expectations;
    public String personal_contact_number;
    public String personal_email;
    public String personal_hobbies;
    public String pincode;
    public String pob;
    public String reference_address;
    public String reference_contact_no;
    public String reference_name;
    public String religion;
    public String state;
    public String tob;
    public String total_brothers;
    public String total_sisters;

    public void onBackPressed() {
    }

    public FamilyDetailsActivity() {
        String str = "";
        this.education_details_two = str;
        this.education_details_three = str;
        this.father_name = str;
        this.fathers_occupation = str;
        this.mother_name = str;
        this.mothers_occupation = str;
        this.grand_father_name = str;
        this.grand_mother_name = str;
        this.total_brothers = str;
        this.married_brothers = str;
        this.parents_contact = str;
        this.partner_expectations = str;
        this.address_line1 = str;
        this.address_line2 = str;
        this.district = str;
        this.state = str;
        this.pincode = str;
        this.reference_name = str;
        this.reference_contact_no = str;
        this.reference_address = str;
    }

    /* Access modifiers changed, original: protected */
    public void onCreate(Bundle bundle) {
        super.onCreate(bundle);
        setContentView((int) R.layout.activity_family_details);
        this.input_father_name = (EditText) findViewById(R.id.input_father_name);
        this.input_fathers_occupation = (EditText) findViewById(R.id.input_fathers_occupation);
        this.input_mother_name = (EditText) findViewById(R.id.input_mother_name);
        this.input_mothers_occupation = (EditText) findViewById(R.id.input_mothers_occupation);
        this.input_grand_father_name = (EditText) findViewById(R.id.input_grand_father_name);
        this.input_grand_mother_name = (EditText) findViewById(R.id.input_grand_mother_name);
        this.input_total_brothers = (EditText) findViewById(R.id.input_total_brothers);
        this.input_married_brothers = (EditText) findViewById(R.id.input_married_brothers);
        this.input_total_sisters = (EditText) findViewById(R.id.input_total_sisters);
        this.input_parental_uncle_aunt = (EditText) findViewById(R.id.input_parental_uncle_aunt);
        this.input_maternal_uncle_aunt = (EditText) findViewById(R.id.input_maternal_uncle_aunt);
        this.input_parents_contact_number = (EditText) findViewById(R.id.input_parents_contact_number);
        this.input_partner_expectations = (EditText) findViewById(R.id.input_partner_expectations);
        Intent intent = getIntent();
        this.full_name = intent.getStringExtra("full_name");
        this.religion = intent.getStringExtra("religion");
        this.caste = intent.getStringExtra("caste");
        this.dob = intent.getStringExtra("dob");
        this.age = intent.getStringExtra("age");
        this.height = intent.getStringExtra(HtmlTags.HEIGHT);
        this.blood_group = intent.getStringExtra("blood_group");
        this.complexion = intent.getStringExtra("complexion");
        this.personal_contact_number = intent.getStringExtra("personal_contact_number");
        this.personal_email = intent.getStringExtra("personal_email");
        this.personal_hobbies = intent.getStringExtra("personal_hobbies");
        this.tob = intent.getStringExtra("tob");
        this.pob = intent.getStringExtra("pob");
        this.mangal = intent.getStringExtra("mangal");
        this.gotra = intent.getStringExtra("gotra");
        this.education_details = intent.getStringExtra("education_details");
        this.education_details_two = intent.getStringExtra("education_details_two");
        this.education_details_three = intent.getStringExtra("education_details_three");
        this.education_address = intent.getStringExtra("education_address");
        this.occupation_details = intent.getStringExtra("occupation_details");
        this.income_details = intent.getStringExtra("income_details");
        this.father_name = intent.getStringExtra("father_name");
        this.fathers_occupation = intent.getStringExtra("fathers_occupation");
        this.mother_name = intent.getStringExtra("mother_name");
        this.mothers_occupation = intent.getStringExtra("mothers_occupation");
        this.grand_father_name = intent.getStringExtra("grand_father_name");
        this.grand_mother_name = intent.getStringExtra("grand_mother_name");
        this.total_brothers = intent.getStringExtra("total_brothers");
        this.married_brothers = intent.getStringExtra("married_brothers");
        this.total_sisters = intent.getStringExtra("total_sisters");
        this.parents_contact = intent.getStringExtra("parents_contact");
        this.partner_expectations = intent.getStringExtra("partner_expectations");
        this.address_line1 = intent.getStringExtra("address_line1");
        this.address_line2 = intent.getStringExtra("address_line2");
        this.district = intent.getStringExtra("district");
        this.state = intent.getStringExtra("state");
        this.pincode = intent.getStringExtra("pincode");
        this.reference_name = intent.getStringExtra("reference_name");
        this.reference_contact_no = intent.getStringExtra("reference_contact_no");
        this.reference_address = intent.getStringExtra("reference_address");
        this.input_father_name.setText(this.father_name);
        this.input_fathers_occupation.setText(this.fathers_occupation);
        this.input_mother_name.setText(this.mother_name);
        this.input_mothers_occupation.setText(this.mothers_occupation);
        this.input_grand_father_name.setText(this.grand_father_name);
        this.input_grand_mother_name.setText(this.grand_mother_name);
        this.input_total_brothers.setText(this.total_brothers);
        this.input_married_brothers.setText(this.married_brothers);
        this.input_parental_uncle_aunt.setText(Constant.paternal_uncle_aunt);
        this.input_maternal_uncle_aunt.setText(Constant.maternal_uncle_aunt);
        this.input_parents_contact_number.setText(this.parents_contact);
        this.input_partner_expectations.setText(this.partner_expectations);
        Button button = (Button) findViewById(R.id.back);
        this.back = button;
        button.setOnClickListener(new OnClickListener() {
            public void onClick(View view) {
                FamilyDetailsActivity.this.backData();
                FamilyDetailsActivity.this.finish();
            }
        });
        button = (Button) findViewById(R.id.next);
        this.next = button;
        button.setOnClickListener(new OnClickListener() {
            public void onClick(View view) {
                FamilyDetailsActivity.this.familyDetails();
            }
        });
        button = (Button) findViewById(R.id.next2);
        this.next2 = button;
        button.setOnClickListener(new OnClickListener() {
            public void onClick(View view) {
                FamilyDetailsActivity.this.familyDetails();
            }
        });
    }

    public void familyDetails() {
        this.input_father_name1 = this.input_father_name.getText().toString();
        this.input_fathers_occupation1 = this.input_fathers_occupation.getText().toString();
        this.input_mother_name1 = this.input_mother_name.getText().toString();
        this.input_mothers_occupation1 = this.input_mothers_occupation.getText().toString();
        this.input_grand_father_name1 = this.input_grand_father_name.getText().toString();
        this.input_grand_mother_name1 = this.input_grand_mother_name.getText().toString();
        this.input_total_brothers1 = this.input_total_brothers.getText().toString();
        this.input_married_brothers1 = this.input_married_brothers.getText().toString();
        this.input_total_sisters1 = this.input_total_sisters.getText().toString();
        Constant.paternal_uncle_aunt = this.input_parental_uncle_aunt.getText().toString();
        Constant.maternal_uncle_aunt = this.input_maternal_uncle_aunt.getText().toString();
        this.input_parents_contact_number1 = this.input_parents_contact_number.getText().toString();
        this.input_partner_expectations1 = this.input_partner_expectations.getText().toString();
        Intent intent = new Intent(getApplicationContext(), AddressDetailsActivity.class);
        intent.putExtra("full_name", this.full_name);
        intent.putExtra("religion", this.religion);
        intent.putExtra("caste", this.caste);
        intent.putExtra("dob", this.dob);
        intent.putExtra("age", this.age);
        intent.putExtra(HtmlTags.HEIGHT, this.height);
        intent.putExtra("blood_group", this.blood_group);
        intent.putExtra("complexion", this.complexion);
        intent.putExtra("personal_contact_number", this.personal_contact_number);
        intent.putExtra("personal_email", this.personal_email);
        intent.putExtra("personal_hobbies", this.personal_hobbies);
        intent.putExtra("tob", this.tob);
        intent.putExtra("pob", this.pob);
        intent.putExtra("mangal", this.mangal);
        intent.putExtra("gotra", this.gotra);
        intent.putExtra("education_details", this.education_details);
        intent.putExtra("education_details_two", this.education_details_two);
        intent.putExtra("education_details_three", this.education_details_three);
        intent.putExtra("education_address", this.education_address);
        intent.putExtra("occupation_details", this.occupation_details);
        intent.putExtra("income_details", this.income_details);
        intent.putExtra("father_name", this.input_father_name1);
        intent.putExtra("fathers_occupation", this.input_fathers_occupation1);
        intent.putExtra("mother_name", this.input_mother_name1);
        intent.putExtra("mothers_occupation", this.input_mothers_occupation1);
        intent.putExtra("grand_father_name", this.input_grand_father_name1);
        intent.putExtra("grand_mother_name", this.input_grand_mother_name1);
        intent.putExtra("total_brothers", this.input_total_brothers1);
        intent.putExtra("married_brothers", this.input_married_brothers1);
        intent.putExtra("total_sisters", this.input_total_sisters1);
        intent.putExtra("parents_contact", this.input_parents_contact_number1);
        intent.putExtra("partner_expectations", this.input_partner_expectations1);
        intent.putExtra("address_line1", this.address_line1);
        intent.putExtra("address_line2", this.address_line2);
        intent.putExtra("district", this.district);
        intent.putExtra("state", this.state);
        intent.putExtra("pincode", this.pincode);
        intent.putExtra("reference_name", this.reference_name);
        intent.putExtra("reference_contact_no", this.reference_contact_no);
        intent.putExtra("reference_address", this.reference_address);
        startActivity(intent);
    }

    public void backData() {
        this.input_father_name1 = this.input_father_name.getText().toString();
        this.input_fathers_occupation1 = this.input_fathers_occupation.getText().toString();
        this.input_mother_name1 = this.input_mother_name.getText().toString();
        this.input_mothers_occupation1 = this.input_mothers_occupation.getText().toString();
        this.input_grand_father_name1 = this.input_grand_father_name.getText().toString();
        this.input_grand_mother_name1 = this.input_grand_mother_name.getText().toString();
        this.input_total_brothers1 = this.input_total_brothers.getText().toString();
        this.input_married_brothers1 = this.input_married_brothers.getText().toString();
        this.input_total_sisters1 = this.input_total_sisters.getText().toString();
        this.input_parents_contact_number1 = this.input_parents_contact_number.getText().toString();
        this.input_partner_expectations1 = this.input_partner_expectations.getText().toString();
        Intent intent = new Intent(getApplicationContext(), EducationDetailsActivity.class);
        intent.putExtra("full_name", this.full_name);
        intent.putExtra("religion", this.religion);
        intent.putExtra("caste", this.caste);
        intent.putExtra("dob", this.dob);
        intent.putExtra("age", this.age);
        intent.putExtra(HtmlTags.HEIGHT, this.height);
        intent.putExtra("blood_group", this.blood_group);
        intent.putExtra("complexion", this.complexion);
        intent.putExtra("personal_contact_number", this.personal_contact_number);
        intent.putExtra("personal_email", this.personal_email);
        intent.putExtra("personal_hobbies", this.personal_hobbies);
        intent.putExtra("tob", this.tob);
        intent.putExtra("pob", this.pob);
        intent.putExtra("mangal", this.mangal);
        intent.putExtra("gotra", this.gotra);
        intent.putExtra("education_details", this.education_details);
        intent.putExtra("education_details_two", this.education_details_two);
        intent.putExtra("education_details_three", this.education_details_three);
        intent.putExtra("education_address", this.education_address);
        intent.putExtra("occupation_details", this.occupation_details);
        intent.putExtra("income_details", this.income_details);
        intent.putExtra("father_name", this.input_father_name1);
        intent.putExtra("fathers_occupation", this.input_fathers_occupation1);
        intent.putExtra("mother_name", this.input_mother_name1);
        intent.putExtra("mothers_occupation", this.input_mothers_occupation1);
        intent.putExtra("grand_father_name", this.input_grand_father_name1);
        intent.putExtra("grand_mother_name", this.input_grand_mother_name1);
        intent.putExtra("total_brothers", this.input_total_brothers1);
        intent.putExtra("married_brothers", this.input_married_brothers1);
        intent.putExtra("total_sisters", this.input_total_sisters1);
        intent.putExtra("parents_contact", this.input_parents_contact_number1);
        intent.putExtra("partner_expectations", this.input_partner_expectations1);
        intent.putExtra("address_line1", this.address_line1);
        intent.putExtra("address_line2", this.address_line2);
        intent.putExtra("district", this.district);
        intent.putExtra("state", this.state);
        intent.putExtra("pincode", this.pincode);
        intent.putExtra("reference_name", this.reference_name);
        intent.putExtra("reference_contact_no", this.reference_contact_no);
        intent.putExtra("reference_address", this.reference_address);
        startActivity(intent);
    }

    private void createPdf() {
        StringBuilder stringBuilder;
        String str = "PDFCreator";
        Document document = new Document();
        try {
            String file = Environment.getExternalStorageDirectory().toString();
            StringBuilder stringBuilder2 = new StringBuilder();
            stringBuilder2.append(file);
            stringBuilder2.append("/resumepdf");
            File file2 = new File(stringBuilder2.toString());
            file2.mkdirs();
            PdfWriter.getInstance(document, new FileOutputStream(new File(file2, "sample.pdf")));
            document.open();
            Paragraph paragraph = new Paragraph("Sample PDF CREATION USING IText");
            Font font = new Font(FontFamily.COURIER);
            paragraph.setAlignment(1);
            paragraph.setFont(font);
            document.add(paragraph);
            paragraph = new Paragraph("This is an example of a simple paragraph");
            font = new Font(FontFamily.COURIER, 14.0f, 0, CMYKColor.GREEN);
            paragraph.setAlignment(1);
            paragraph.setFont(font);
            document.add(paragraph);
            ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
            BitmapFactory.decodeResource(getBaseContext().getResources(), R.mipmap.ic_launcher).compress(CompressFormat.JPEG, 100, byteArrayOutputStream);
            Image instance = Image.getInstance(byteArrayOutputStream.toByteArray());
            instance.setAlignment(1);
            document.add(instance);
        } catch (DocumentException e) {
            stringBuilder = new StringBuilder();
            stringBuilder.append("DocumentException:");
            stringBuilder.append(e);
            Log.e(str, stringBuilder.toString());
        } catch (IOException e2) {
            stringBuilder = new StringBuilder();
            stringBuilder.append("ioException:");
            stringBuilder.append(e2);
            Log.e(str, stringBuilder.toString());
        } catch (Throwable th) {
            document.close();
        }
        document.close();
    }
}
