package decompile.apk.activity;

import Adapter.FrameCategoryRecycleAdapter;
import Adapter.TextureCategoryRecycleAdapter;
import ModelClass.FrameCategoryModelClass;
import ModelClass.TextureCategoryModelClass;
import android.content.Intent;
import android.os.Bundle;
import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.DefaultItemAnimator;
import androidx.recyclerview.widget.GridLayoutManager;
import androidx.recyclerview.widget.RecyclerView;
import com.asharinfotech.muslimweddingcard.R;
import com.itextpdf.text.html.HtmlTags;
import java.util.ArrayList;

public class FrameSelectActivity extends AppCompatActivity {
    public String address_line1;
    public String address_line2;
    public String age;
    public String blood_group;
    public String caste;
    public String complexion;
    public String district;
    public String dob;
    public String education_address;
    public String education_details;
    public String education_details_three;
    public String education_details_two;
    public String father_name;
    public String fathers_occupation;
    private ArrayList<FrameCategoryModelClass> frameCategoryModelClasses;
    private FrameCategoryRecycleAdapter frameCategoryRecycleAdapter;
    public String full_name;
    public String gotra;
    public String grand_father_name;
    public String grand_mother_name;
    public String height;
    private Integer[] image;
    private Integer[] image1;
    public String imagepath;
    public String income_details;
    public String mangal;
    public String married_brothers;
    public String married_sisters;
    public String mother_name;
    public String mothers_occupation;
    public String occupation_details;
    public String parents_contact;
    public String partner_expectations;
    public String personal_contact_number;
    public String personal_email;
    public String personal_hobbies;
    public String pincode;
    public String pob;
    private RecyclerView recyclerView;
    private RecyclerView recyclerView1;
    public String reference_address;
    public String reference_contact_no;
    public String reference_name;
    public String religion;
    public String state;
    private ArrayList<TextureCategoryModelClass> textureCategoryModelClasses;
    private TextureCategoryRecycleAdapter textureCategoryRecycleAdapter;
    private String[] title = new String[]{"No Frame", "Frame One", "Frame Two", "Frame Three", "Frame Four", "Frame Five", "Frame Six", "Frame Seven", "Frame Eight", "Frame Nine", "Frame Ten", "Frame Eleven", "Frame Twelve", "Frame Thirteen", "Frame Fourteen", "Frame Fifteen", "Frame Sixteen", "Frame Seventeen"};
    private String[] title1;
    public String tob;
    public String total_brothers;
    public String total_sisters;

    public FrameSelectActivity() {
        r2 = new Integer[18];
        r2[0] = Integer.valueOf(R.drawable.ic_baseline_image_not_supported_24);
        r2[1] = Integer.valueOf(R.drawable.frame_one);
        r2[2] = Integer.valueOf(R.drawable.frame_two);
        r2[3] = Integer.valueOf(R.drawable.frame_three);
        r2[4] = Integer.valueOf(R.drawable.frame_four);
        r2[5] = Integer.valueOf(R.drawable.frame_five);
        r2[6] = Integer.valueOf(R.drawable.frame_six);
        r2[7] = Integer.valueOf(R.drawable.frame_seven);
        r2[8] = Integer.valueOf(R.drawable.frame_eight);
        r2[9] = Integer.valueOf(R.drawable.frame_nine);
        r2[10] = Integer.valueOf(R.drawable.frame_ten);
        r2[11] = Integer.valueOf(R.drawable.frame_eleven);
        r2[12] = Integer.valueOf(R.drawable.frame_twelve);
        r2[13] = Integer.valueOf(R.drawable.frame_thirteen);
        r2[14] = Integer.valueOf(R.drawable.frame_fourteen);
        r2[15] = Integer.valueOf(R.drawable.frame_fifteen);
        r2[16] = Integer.valueOf(R.drawable.frame_sixteen);
        r2[17] = Integer.valueOf(R.drawable.frame_seventeen);
        this.image = r2;
        this.image1 = new Integer[]{r3, Integer.valueOf(R.drawable.texture_one), Integer.valueOf(R.drawable.texture_two), Integer.valueOf(R.drawable.texture_three), Integer.valueOf(R.drawable.texture_four), Integer.valueOf(R.drawable.texture_five), Integer.valueOf(R.drawable.texture_six), Integer.valueOf(R.drawable.texture_seven), Integer.valueOf(R.drawable.texture_eight), Integer.valueOf(R.drawable.texture_nine), Integer.valueOf(R.drawable.texture_ten), Integer.valueOf(R.drawable.texture_eleven), Integer.valueOf(R.drawable.texture_twelve), Integer.valueOf(R.drawable.texture_thirteen), Integer.valueOf(R.drawable.texture_fourteen), Integer.valueOf(R.drawable.texture_fifteen), Integer.valueOf(R.drawable.texture_sixteen), Integer.valueOf(R.drawable.texture_seventeen), Integer.valueOf(R.drawable.texture_eighteen), Integer.valueOf(R.drawable.texture_nineteen), Integer.valueOf(R.drawable.texture_twenty)};
        this.title1 = new String[]{"No Texture", "Texture One", "Texture Two", "Texture Three", "Texture Four", "Texture Five", "Texture Six", "Texture Seven", "Texture Eight", "Texture Nine", "Texture Ten", "Texture Eleven", "Texture Twelve", "Texture Thirteen", "Texture Fourteen", "Texture Fifteen", "Texture Sixteen", "Texture Seventeen", "Texture Eighteen", "Texture Nineteen", "Texture Twenty"};
        String str = "";
        this.education_details_two = str;
        this.education_details_three = str;
        this.father_name = str;
        this.fathers_occupation = str;
        this.mother_name = str;
        this.mothers_occupation = str;
        this.grand_father_name = str;
        this.grand_mother_name = str;
        this.total_brothers = str;
        this.married_brothers = str;
    }

    /* Access modifiers changed, original: protected */
    public void onCreate(Bundle bundle) {
        Integer[] numArr;
        super.onCreate(bundle);
        setContentView((int) R.layout.activity_frame_select);
        Intent intent = getIntent();
        String str = "full_name";
        this.full_name = intent.getStringExtra(str);
        String str2 = "religion";
        this.religion = intent.getStringExtra(str2);
        String str3 = "caste";
        this.caste = intent.getStringExtra(str3);
        String str4 = "dob";
        this.dob = intent.getStringExtra(str4);
        String str5 = "age";
        this.age = intent.getStringExtra(str5);
        String str6 = HtmlTags.HEIGHT;
        this.height = intent.getStringExtra(str6);
        String str7 = "blood_group";
        this.blood_group = intent.getStringExtra(str7);
        String str8 = "complexion";
        this.complexion = intent.getStringExtra(str8);
        String str9 = "personal_contact_number";
        this.personal_contact_number = intent.getStringExtra(str9);
        String str10 = "personal_email";
        this.personal_email = intent.getStringExtra(str10);
        String str11 = "personal_hobbies";
        this.personal_hobbies = intent.getStringExtra(str11);
        String str12 = "tob";
        this.tob = intent.getStringExtra(str12);
        String str13 = "pob";
        this.pob = intent.getStringExtra(str13);
        String str14 = "mangal";
        String str15 = str13;
        this.mangal = intent.getStringExtra(str14);
        str13 = "gotra";
        String str16 = str14;
        this.gotra = intent.getStringExtra(str13);
        str14 = "education_details";
        String str17 = str13;
        this.education_details = intent.getStringExtra(str14);
        str13 = "education_details_two";
        String str18 = str14;
        this.education_details_two = intent.getStringExtra(str13);
        str14 = "education_details_three";
        String str19 = str13;
        this.education_details_three = intent.getStringExtra(str14);
        str13 = "education_address";
        String str20 = str14;
        this.education_address = intent.getStringExtra(str13);
        str14 = "occupation_details";
        String str21 = str13;
        this.occupation_details = intent.getStringExtra(str14);
        str13 = "income_details";
        String str22 = str14;
        this.income_details = intent.getStringExtra(str13);
        str14 = "father_name";
        String str23 = str13;
        this.father_name = intent.getStringExtra(str14);
        this.fathers_occupation = intent.getStringExtra("fathers_occupation");
        this.mother_name = intent.getStringExtra("mother_name");
        this.mothers_occupation = intent.getStringExtra("mothers_occupation");
        this.grand_father_name = intent.getStringExtra("grand_father_name");
        this.grand_mother_name = intent.getStringExtra("grand_mother_name");
        this.total_brothers = intent.getStringExtra("total_brothers");
        this.married_brothers = intent.getStringExtra("married_brothers");
        this.total_sisters = intent.getStringExtra("total_sisters");
        this.parents_contact = intent.getStringExtra("parents_contact");
        this.partner_expectations = intent.getStringExtra("partner_expectations");
        this.address_line1 = intent.getStringExtra("address_line1");
        this.address_line2 = intent.getStringExtra("address_line2");
        this.district = intent.getStringExtra("district");
        this.state = intent.getStringExtra("state");
        this.pincode = intent.getStringExtra("pincode");
        this.reference_name = intent.getStringExtra("reference_name");
        this.reference_contact_no = intent.getStringExtra("reference_contact_no");
        this.reference_address = intent.getStringExtra("reference_address");
        this.imagepath = intent.getStringExtra("imagepath");
        Bundle bundle2 = new Bundle();
        bundle2.putString(str, this.full_name);
        bundle2.putString(str2, this.religion);
        bundle2.putString(str3, this.caste);
        bundle2.putString(str4, this.dob);
        bundle2.putString(str5, this.age);
        bundle2.putString(str6, this.height);
        bundle2.putString(str7, this.blood_group);
        bundle2.putString(str8, this.complexion);
        bundle2.putString(str9, this.personal_contact_number);
        bundle2.putString(str10, this.personal_email);
        bundle2.putString(str11, this.personal_hobbies);
        bundle2.putString(str12, this.tob);
        bundle2.putString(str15, this.pob);
        bundle2.putString(str16, this.mangal);
        bundle2.putString(str17, this.gotra);
        bundle2.putString(str18, this.education_details);
        bundle2.putString(str19, this.education_details_two);
        bundle2.putString(str20, this.education_details_three);
        bundle2.putString(str21, this.education_address);
        bundle2.putString(str22, this.occupation_details);
        bundle2.putString(str23, this.income_details);
        bundle2.putString(str14, this.father_name);
        bundle2.putString("fathers_occupation", this.fathers_occupation);
        bundle2.putString("mother_name", this.mother_name);
        bundle2.putString("mothers_occupation", this.mothers_occupation);
        bundle2.putString("grand_father_name", this.grand_father_name);
        bundle2.putString("grand_mother_name", this.grand_mother_name);
        bundle2.putString("total_brothers", this.total_brothers);
        bundle2.putString("married_brothers", this.married_brothers);
        bundle2.putString("total_sisters", this.total_sisters);
        bundle2.putString("parents_contact", this.parents_contact);
        bundle2.putString("partner_expectations", this.partner_expectations);
        bundle2.putString("address_line1", this.address_line1);
        bundle2.putString("address_line2", this.address_line2);
        bundle2.putString("district", this.district);
        bundle2.putString("state", this.state);
        bundle2.putString("pincode", this.pincode);
        bundle2.putString("reference_name", this.reference_name);
        bundle2.putString("reference_contact_no", this.reference_contact_no);
        bundle2.putString("reference_address", this.reference_address);
        bundle2.putString("imagepath", this.imagepath);
        this.recyclerView = (RecyclerView) findViewById(R.id.CategoryRecyclerview);
        this.recyclerView.setLayoutManager(new GridLayoutManager(getApplicationContext(), 3));
        this.recyclerView.setItemAnimator(new DefaultItemAnimator());
        this.frameCategoryModelClasses = new ArrayList();
        int i = 0;
        while (true) {
            numArr = this.image;
            if (i >= numArr.length) {
                break;
            }
            this.frameCategoryModelClasses.add(new FrameCategoryModelClass(numArr[i], this.title[i]));
            i++;
        }
        FrameCategoryRecycleAdapter frameCategoryRecycleAdapter = new FrameCategoryRecycleAdapter(getApplicationContext(), this.frameCategoryModelClasses, bundle2);
        this.frameCategoryRecycleAdapter = frameCategoryRecycleAdapter;
        this.recyclerView.setAdapter(frameCategoryRecycleAdapter);
        this.recyclerView1 = (RecyclerView) findViewById(R.id.TextureRecyclerview);
        this.recyclerView1.setLayoutManager(new GridLayoutManager(getApplicationContext(), 3));
        this.recyclerView1.setItemAnimator(new DefaultItemAnimator());
        this.textureCategoryModelClasses = new ArrayList();
        i = 0;
        while (true) {
            numArr = this.image1;
            if (i < numArr.length) {
                this.textureCategoryModelClasses.add(new TextureCategoryModelClass(numArr[i], this.title1[i]));
                i++;
            } else {
                TextureCategoryRecycleAdapter textureCategoryRecycleAdapter = new TextureCategoryRecycleAdapter(getApplicationContext(), this.textureCategoryModelClasses, bundle2);
                this.textureCategoryRecycleAdapter = textureCategoryRecycleAdapter;
                this.recyclerView1.setAdapter(textureCategoryRecycleAdapter);
                return;
            }
        }
    }
}
